export const defaultRoomValues = {
    title: "",
    description: "",
    bedCount: 0,
    guestCount: 0,
    bathRoomCount: 0,
    kingBed: 0,
    queenBen: 0,
    image: "",
    breakFastPrice: 0,
    roomPrice: 0,
    cityView: false,
    roomView: false,
    mountainView: false,
    airCondition: false,
    soundProof: false,
    balcony: false,
    privateBatroom: false,
    hotelId: "",
} 