export const defaultHotelValues = {
  title: "",
  description: "",
  images: [],
  country: "",
  state: "",
  city: "",
  locationDescription: "",
  gym: false,
  pool: false,
  spa: false,
  sauna: false,
  freeWifi: false,
  airConditioning: false,
  tv: false,
  restaurant: false,
  bar: false,
  roomService: false,
  parking: false,
  isFeatured: false,
  coffeeShop: false,
};